### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by TetroYT** [iZeaoGamer/WorldBorder#1]
border walls like on pc

if thats even possible on mcpe 
![245B1F4F-F662-4BD8-8C96-9AAE81319985](https://user-images.githubusercontent.com/49662383/76431255-3d763000-63a9-11ea-8e70-45a59cdc6389.png)

**Comment by iZeaoGamer** [comment]
I've been doing some research on this, and I don't think pocketmine has implemented this yet, nor has any plugins made this plugin yet. I don't even know if this is properly in MCPE or not, as well as Pocketmine's implementation to it, which I doubt they have.
