### ISSUE TITLE
can add All World border？

### ISSUE THREAD

**Issue by junxiesky** [iZeaoGamer/WorldBorder#2]
Can you add all the world border?

**Comment by iZeaoGamer** [comment]
I don’t understand the question. Could you elaborate?

**Comment by junxiesky** [comment]
> I don’t understand the question. Could you elaborate?

What I mean is: set the edges of all worlds, not just individual worlds.

**Comment by iZeaoGamer** [comment]
So basically, you want me to implement a way so the plugin works in all worlds?

**Comment by junxiesky** [comment]
> 因此，基本上，您希望我实现一种使插件在所有世界都能正常工作的方法吗？

yes

**Comment by iZeaoGamer** [comment]
Okay. I’ll see what I can do. I’ll keep this opened until I add this.

**Comment by junxiesky** [comment]
> So basically, you want me to implement a way so the plugin works in all worlds?

Because my server is an empty island server.
I need to control the size of each island world.

**Comment by junxiesky** [comment]
> Okay. I’ll see what I can do. I’ll keep this opened until I add this.

thanks~

**Comment by iZeaoGamer** [comment]
Oh, I see. I was completely thinking of something else lol. Not sure if I can do that, but I’ll look into it. Though, if you were to set the edges of all worlds AKA edit the range per world, then configurations would most probably be messy, and I don’t like a messy config.

**Comment by junxiesky** [comment]
> 哦，我懂了。我完全在想别的事情。不知道我是否可以这样做，但是我会调查一下。但是，如果要设置所有世界的边缘，也可以编辑每个世界的范围，那么配置很可能会很混乱，我不喜欢混乱的配置。

ummm,okay

**Comment by iZeaoGamer** [comment]
I’m sorry, but I’m going to close this issue.
This is because I don’t want a messy configuration, in which may be required if we were going to implement this future.
