### ISSUE TITLE
Loading Crash

### ISSUE THREAD

**Issue by suerion** [iZeaoGamer/WorldBorder#7]
I allways get an crash from WorldBorder,

> 2020-04-22 [15:54:25] [Server thread/CRITICAL]: Error: "Call to undefined method pocketmine\command\Command::__consturct()" (EXCEPTION) in "plugins/WorldBorder.phar/src/iZeaoGamer/WorldBorder/commands/WorldBorderCommand" at line 13
> 2020-04-22 [15:54:25] [Server thread/DEBUG]: #0 plugins/WorldBorder.phar/src/iZeaoGamer/WorldBorder/Main(49): iZeaoGamer\WorldBorder\commands\WorldBorderCommand->__construct(object iZeaoGamer\WorldBorder\Main)
> 2020-04-22 [15:54:25] [Server thread/DEBUG]: #1 src/pocketmine/plugin/PluginBase(115): iZeaoGamer\WorldBorder\Main->onEnable()
> 2020-04-22 [15:54:25] [Server thread/DEBUG]: #2 src/pocketmine/plugin/PluginManager(541): pocketmine\plugin\PluginBase->setEnabled(boolean 1)
> 2020-04-22 [15:54:25] [Server thread/DEBUG]: #3 src/pocketmine/Server(1783): pocketmine\plugin\PluginManager->enablePlugin(object iZeaoGamer\WorldBorder\Main)
> 2020-04-22 [15:54:25] [Server thread/DEBUG]: #4 src/pocketmine/Server(1769): pocketmine\Server->enablePlugin(object iZeaoGamer\WorldBorder\Main)
> 2020-04-22 [15:54:25] [Server thread/DEBUG]: #5 src/pocketmine/Server(1582): pocketmine\Server->enablePlugins(integer 1)
> 2020-04-22 [15:54:25] [Server thread/DEBUG]: #6 src/pocketmine/PocketMine(273): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[49] /home/minecraft/multicraft/servers/PE/pocketmine/, string[57] /home/minecraft/multicraft/servers/PE/pocketmine/plugins/)
> 2020-04-22 [15:54:25] [Server thread/DEBUG]: #7 src/pocketmine/PocketMine(296): pocketmine\server()
> 2020-04-22 [15:54:25] [Server thread/DEBUG]: #8 (11): require(string[104] phar:///home/minecraft/multicraft/servers/PE/pocketmine/PocketMine-MP.phar/src/p)

**Comment by iZeaoGamer** [comment]
Please install the latest dev build from poggit. This issue was resolved.

**Comment by suerion** [comment]
Thanks, i did download the dev build yet
